### ISSUE TITLE
Release of code and dataset

### ISSUE THREAD

**Issue by haofanwang** [AIGText/Glyph-ByT5#1]
Hi, thanks for this excellent work! Any update for the inference code and dataset? Furthermore, is there a plan for releasing training code together?

**Comment by hanquansanren** [comment]
same request, much thank to your great work!

**Comment by NitishG20** [comment]
@PkuRainBow When can we expect the training code to be shared?

**Comment by lzy-tony** [comment]
Hi, thanks for you comment! Weights and pretraining dataset/code have been released. Please check it out!

**Comment by willpat1213** [comment]
Can someone share a previously open source code and weights? The author deleted the code and weights for some reason.
My Email: yangliu1213@hust.edu.cn
Thanks!
