### ISSUE TITLE
代码被删除

### ISSUE THREAD

**Issue by JoshonSmith** [AIGText/Glyph-ByT5#14]
请问之前开源的代码如今被删除了
有什么顾虑吗

**Comment by h3clikejava** [comment]
为啥你要close this issue?

**Comment by JoshonSmith** [comment]
> 为啥你要close this issue?

作者已经回复：
2024.06.28 We have removed the weights and code that may have used potentially unauthorized datasets in the current stage. We will update the checkpoints after the Microsoft RAI process.
