### ISSUE TITLE
以下代码缺失，请问会补全代码么？

### ISSUE THREAD

**Issue by pljj315** [AIGText/Glyph-ByT5#7]
路径Glyph-ByT5/inference/glyph_sdxl/custom_diffusers/下代码文件缺失了一部分，请问会补全么？

![image](https://github.com/AIGText/Glyph-ByT5/assets/85743914/e4addc09-ebc0-4993-8724-b49b1c347691)
![image](https://github.com/AIGText/Glyph-ByT5/assets/85743914/aaa94760-9e37-46d9-bda2-ff5171885e95)
![image](https://github.com/AIGText/Glyph-ByT5/assets/85743914/ed1177aa-fdae-4aa6-b961-8c3bcab6bcdf)

**Comment by lzy-tony** [comment]
感谢您的关注！也非常抱歉我们的疏忽，这部分代码已经补全了

**Comment by willpat1213** [comment]
官方代码删除了，请问方便发一份代码给我follow一下这篇工作吗
我的邮箱是：yangliu1213@hust.edu.cn
感激不尽！
